dist: xenial
language: python
python:
  - "3.7"

env:
  - QT_QPA_PLATFORM=offscreen
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US:en
  - LC_ALL=en_US.UTF-8

# Using addons rather than apt-get install
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - netcdf-bin
    - libnetcdf-dev
    - libsm6
    - libxext6
    - libxrender-dev
    - libxt6
    - libgl1-mesa-glx
    - libfontconfig
    - libxkbcommon-x11-0
    - locales

before_script:
  - locale-gen en_US.UTF-8

install:
  - pip install boututils